name: Update browserslist database

on:
  schedule:
    - cron: "0 16 * * 5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  browserslist-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup node.js
        uses: volta-cli/action@v4

      - name: Run browserslist update
        run: npm run browserslist-update

      - name: Check for changes
        id: git-diff
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-diff.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json
          git commit -m "update browserslist database"
          git push
