name: Volta Node.js update

on:
  schedule:
    - cron: '0 15 * * 5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  volta-node-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup volta
        uses: volta-cli/action@v4

      - name: Run volta pin node
        run: volta pin node@24

      - name: Check for changes
        id: git-diff
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-diff.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "update node version in volta config"
          git push
